# Generated by Django 3.1.5 on 2021-04-07 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coworking.booking')),
            ],
        ),
    ]
