# Generated by Django 3.1.5 on 2021-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_order_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='period',
            field=models.IntegerField(choices=[(1, 'День'), (3, 'Три дня'), (7, 'Неделя'), (30, 'Месяц'), (181, 'Полгода')], default=1),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
