# Generated by Django 3.1.5 on 2021-04-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0007_auto_20210408_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.IntegerField(choices=[(3, 'Младший менеджер'), (2, 'Менеджер'), (1, 'Старший менеджер')], default=2),
        ),
    ]
